// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlW2K4R1YEaXl47OfGLz0pvFJv82ixt2s',
    appId: '1:337966083365:web:52fda5af9b7143f8ca3ecc',
    messagingSenderId: '337966083365',
    projectId: 'track-me-f6244',
    authDomain: 'track-me-f6244.firebaseapp.com',
    storageBucket: 'track-me-f6244.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJWH4fUkfNPYTezNbaYYDpu88QwuUKeCg',
    appId: '1:337966083365:android:3e979fe7528cf916ca3ecc',
    messagingSenderId: '337966083365',
    projectId: 'track-me-f6244',
    storageBucket: 'track-me-f6244.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZgIBl7DHacgZw0ExnE9kXXfGwv4AhrJ8',
    appId: '1:337966083365:ios:b08e13bfff0d4d25ca3ecc',
    messagingSenderId: '337966083365',
    projectId: 'track-me-f6244',
    storageBucket: 'track-me-f6244.appspot.com',
    iosClientId: '337966083365-ah4dt865oh4t6pnod6jro8uao9kj6lql.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackMe',
  );
}
